<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Book;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $authors = [
            [
                'name' => 'Abdulla Qodiriy',
                'birth_date' => '10.04.1894',
                'death_date' => '04.10.1938',
                'birth_place' => 'Toshkent, Turkiston general-gubernatorligi',
                'nationality' => 'O\'zbek',
                'biography' => 'Abdulla Qodiriy — o\'zbek yangi davr realistik nasrining asoschisi, jurnalist, tarjimon va dramaturg. U o\'z ijodida xalq hayotini, milliy ozodlik g\'oyalarini va insoniy fazilatlarni teran tasvirlagan. Ilk asarlari 1910-yillarda matbuotda chop etilgan.',
                'legacy' => 'Uning "O\'tkan kunlar" va "Mehrobdan chayon" romanlari o\'zbek adabiyotining oltin xazinasiga kirgan. 1938-yilda qatag\'on qurboni bo\'lgan, 1956-yilda oqlangan. Bugungi kunda nomi maktab va ko\'chalarga berilgan, mukofotlar ta\'sis etilgan.',
                'image_url' => 'images/authors/abdulla-qodiriy.jpg',
            ],
            [
                'name' => 'Xudoyberdi To\'xtaboyev',
                'birth_date' => '17.12.1932',
                'death_date' => '21.03.2021',
                'birth_place' => 'Farg\'ona viloyati, O\'zbekiston',
                'nationality' => 'O\'zbek',
                'biography' => 'Xudoyberdi To\'xtaboyev — o\'zbek bolalar adabiyotining yorqin namoyandasi, yozuvchi va publitsist. U bolalar uchun yozgan sarguzasht-fantastik asarlari bilan mashhur. Asarlari ko\'plab tillarga tarjima qilingan.',
                'legacy' => '"Sariq devni minib", "Sariq devning o\'limi" kabi asarlari avlodlar uchun sevimli kitoblarga aylangan. O\'zbekiston Xalq yozuvchisi unvoniga sazovor bo\'lgan.',
                'image_url' => 'images/authors/xudoyberdi-toxtaboyev.jpg',
            ],
            [
                'name' => 'Pirimqul Qodirov',
                'birth_date' => '25.10.1928',
                'death_date' => '21.12.2010',
                'birth_place' => 'Istaravshan tumani, Sug\'d viloyati, Tojikiston',
                'nationality' => 'O\'zbek',
                'biography' => 'Pirimqul Qodirov — taniqli o\'zbek yozuvchisi, tarixiy romanlar ustasi. U Bobur va boburiylar sulolasiga oid asarlari bilan kitobxonlar e\'tiborini qozongan.',
                'legacy' => '"Yulduzli tunlar", "Avlodlar dovoni" kabi asarlari o\'zbek tarixiy nasrining cho\'qqilaridan biri. O\'zbekiston Xalq yozuvchisi va Hamza nomidagi mukofot sovrindori.',
                'image_url' => 'images/authors/pirimqul-qodirov.jpg',
            ],
            [
                'name' => 'Paulo Koelo',
                'birth_date' => '24.08.1947',
                'birth_place' => 'Rio-de-Janeyro, Braziliya',
                'nationality' => 'Braziliyalik',
                'biography' => 'Paulo Koelo — dunyoga mashhur Braziliyalik yozuvchi va shoir. U o\'z asarlarida ma\'naviy izlanish, taqdir va orzular mavzusini yorqin yoritgan. Kitoblari 80 dan ortiq tilga tarjima qilingan.',
                'legacy' => '"Al-kimyogar" romani 150 mln. dan ortiq nusxada sotilib, jahon adabiyotining bestselleri bo\'ldi. Frantsiya Faxriy legioni ordeni va ko\'plab xalqaro mukofotlar sohibi.',
                'image_url' => 'images/authors/paulo-koelo.jpg',
            ],
            [
                'name' => 'O\'tkir Hoshimov',
                'birth_date' => '05.08.1941',
                'death_date' => '24.05.2013',
                'birth_place' => 'Toshkent shahri, O\'zbekiston',
                'nationality' => 'O\'zbek',
                'biography' => 'O\'tkir Hoshimov — XX asrning ikkinchi yarmidagi o\'zbek nasrining yetuk vakili. U o\'z asarlarida insoniy fazilatlar, ona mehri, urush va tinchlik mavzularini chuqur tahlil etgan.',
                'legacy' => '"Ikki eshik orasi", "Dunyoning ishlari", "Tushda kechgan umrlar" asarlari avlodlar qalbida muhrlangan. O\'zbekiston Qahramoni va Xalq yozuvchisi unvonlari sohibi.',
                'image_url' => 'images/authors/otkir-hoshimov.jpg',
            ],
            [
                'name' => 'Cho\'lpon',
                'birth_date' => '1897',
                'death_date' => '04.10.1938',
                'birth_place' => 'Andijon, Turkiston general-gubernatorligi',
                'nationality' => 'O\'zbek',
                'biography' => 'Cho\'lpon (Abdulhamid Sulaymon o\'g\'li) — o\'zbek modern she\'riyati va nasrining asoschilaridan biri, jadidchilik harakatining yetakchi vakili. U nazm, nasr, drama va tarjima sohalarida samarali ijod qilgan.',
                'legacy' => '"Kecha va kunduz" romani, lirik she\'rlari milliy uyg\'onish ramzi bo\'lib qoldi. 1938-yilda qatag\'on qilingan, 1956-yilda oqlangan. Hozirda nomi mukofotga berilgan.',
                'image_url' => 'images/authors/cholpon.webp',
            ],
            [
                'name' => 'Tohir Malik',
                'birth_date' => '27.12.1946',
                'death_date' => '16.05.2019',
                'birth_place' => 'Toshkent shahri, O\'zbekiston',
                'nationality' => 'O\'zbek',
                'biography' => 'Tohir Malik — taniqli o\'zbek yozuvchisi, detektiv janrining ustasi. Uning asarlari jinoyat olami va ezgulik kurashini ochib beradi.',
                'legacy' => '"Shaytanat" turkumi (1-4 kitob) o\'zbek detektiv adabiyotining cho\'qqisi sanaladi. O\'zbekiston Xalq yozuvchisi unvoni sohibi.',
                'image_url' => 'images/authors/tohir-malik.jpg',
            ],
            [
                'name' => 'Antuan de Sent-Ekzyuperi',
                'birth_date' => '29.06.1900',
                'death_date' => '31.07.1944',
                'birth_place' => 'Lion, Frantsiya',
                'nationality' => 'Fransuz',
                'biography' => 'Antuan de Sent-Ekzyuperi — fransuz yozuvchisi va harbiy uchuvchi. Uning asarlari insoniylik, do\'stlik va mas\'uliyat haqida falsafiy mushohadalar bilan to\'la.',
                'legacy' => '"Kichkina shahzoda" asari 300 dan ortiq tilga tarjima qilinib, jahon bolalar adabiyotining shoh asariga aylangan. 1944-yilda Ikkinchi jahon urushi paytida halok bo\'lgan.',
                'image_url' => 'images/authors/antuan-de-sent-ekzyuperi.jpg',
            ],
            [
                'name' => 'Jorj Oruell',
                'birth_date' => '25.06.1903',
                'death_date' => '21.01.1950',
                'birth_place' => 'Motixari, Britaniya Hindistoni',
                'nationality' => 'Ingliz',
                'biography' => 'Jorj Oruell (Erik Artur Bler) — ingliz yozuvchisi, publitsist va siyosiy mutafakkir. U totalitarizmga qarshi va ijtimoiy adolat tarafdori sifatida tanilgan.',
                'legacy' => '"1984" va "Molxona" romanlari XX asr antiutopik adabiyotining klassikasi sanaladi. "Orwellian" atamasi uning nomi bilan bog\'liq holda paydo bo\'ldi.',
                'image_url' => 'images/authors/jorj-oruell.webp',
            ],
            [
                'name' => 'Aleksandr Dyuma',
                'birth_date' => '24.07.1802',
                'death_date' => '05.12.1870',
                'birth_place' => 'Vyer-Kotere, Frantsiya',
                'nationality' => 'Fransuz',
                'biography' => 'Aleksandr Dyuma (ota) — XIX asrning eng mashhur fransuz yozuvchilaridan biri. U tarixiy va sarguzasht romanlar ustasi sifatida tanilgan.',
                'legacy' => '"Graf Monte-Kristo", "Uch mushketyor" kabi asarlari jahon adabiyotining bezagi. Kitoblari yuzlab marta filmga olingan va sahnalashtirilgan.',
                'image_url' => 'images/authors/aleksandr-dyuma.webp',
            ],
            [
                'name' => 'Fyodor Dostoyevskiy',
                'birth_date' => '11.11.1821',
                'death_date' => '09.02.1881',
                'birth_place' => 'Moskva, Rossiya imperiyasi',
                'nationality' => 'Rus',
                'biography' => 'Fyodor Dostoyevskiy — jahon adabiyotining buyuk vakillaridan biri, psixologik romannavislik ustasi. U inson ruhiyatining eng tubidagi ziddiyatlarni ochib bergan.',
                'legacy' => '"Jinoyat va jazo", "Karamazov aka-ukalari", "Telba" asarlari jahon adabiyotining cho\'qqisi. Uning asarlari psixologiya, falsafa va din mavzularini birlashtiradi.',
                'image_url' => 'images/authors/fyodor-dostoyevskiy.jpg',
            ],
            [
                'name' => 'Robert Kiyosaki',
                'birth_date' => '08.04.1947',
                'birth_place' => 'Xilo, Gavayi, AQSh',
                'nationality' => 'Amerikalik',
                'biography' => 'Robert Kiyosaki — amerikalik tadbirkor, investor va yozuvchi. U moliyaviy savodxonlik va passiv daromad mavzulariga oid kitoblari bilan mashhur.',
                'legacy' => '"Boy ota, kambag\'al ota" kitobi 40 dan ortiq tilga tarjima qilingan va dunyo bo\'ylab 32 mln. nusxada sotilgan. Rich Dad kompaniyasining asoschisi.',
                'image_url' => 'images/authors/robert-kiyosaki.webp',
            ],
            [
                'name' => 'Uolter Ayzekson',
                'birth_date' => '20.05.1952',
                'birth_place' => 'Nyu-Orlean, Luiziana, AQSh',
                'nationality' => 'Amerikalik',
                'biography' => 'Uolter Ayzekson — amerikalik jurnalist va biograf. U buyuk shaxslar haqidagi chuqur tadqiqotga asoslangan biografiyalari bilan tanilgan.',
                'legacy' => 'Stiv Jobs, Albert Eynshteyn, Leonardo da Vinchi va Benjamin Franklin haqidagi biografiyalari bestseller bo\'ldi. Aspen Institute prezidenti.',
                'image_url' => 'images/authors/uolter-ayzekson.jpg',
            ],
            [
                'name' => 'Yuval Noy Xarari',
                'birth_date' => '24.02.1976',
                'birth_place' => 'Kiryat-Atta, Isroil',
                'nationality' => 'Isroillik',
                'biography' => 'Yuval Noy Xarari — Isroil tarixchisi va Quddus Yahudiy universiteti professori. U insoniyat tarixi, kelajakdagi texnologiyalar va biotexnologiya mavzularida yozadi.',
                'legacy' => '"Sapiens", "Homo Deus", "21-asr uchun 21 saboq" kitoblari 60 dan ortiq tilga tarjima qilingan va 45 mln. nusxada sotilgan.',
                'image_url' => 'images/authors/yuval-noy-xarari.jpg',
            ],
            [
                'name' => 'Stiven Kovi',
                'birth_date' => '24.10.1932',
                'death_date' => '16.07.2012',
                'birth_place' => 'Solt-Leyk-Siti, Yuta, AQSh',
                'nationality' => 'Amerikalik',
                'biography' => 'Stiven Kovi — amerikalik pedagog, ishbilarmon va motivatsion ma\'ruzachi. U shaxsiy rivojlanish va liderlik sohasidagi taniqli mutaxassis edi.',
                'legacy' => '"Muvaffaqiyatli insonlarning 7 ko\'nikmasi" kitobi 40 mln. nusxada sotilgan va 40 ga yaqin tilga tarjima qilingan. FranklinCovey kompaniyasi asoschisi.',
                'image_url' => 'images/authors/stiven-kovi.webp',
            ],
            [
                'name' => 'Artur Konan Doyl',
                'birth_date' => '22.05.1859',
                'death_date' => '07.07.1930',
                'birth_place' => 'Edinburg, Shotlandiya',
                'nationality' => 'Britaniyalik',
                'biography' => 'Ser Artur Konan Doyl — Britaniya yozuvchisi va shifokor. U detektiv adabiyotining mashhur namoyandasi, Sherlok Xolms personajining ijodkori.',
                'legacy' => 'Sherlok Xolms haqidagi 4 ta roman va 56 ta hikoyasi detektiv janrining poydevorini qo\'ydi. 1902-yilda ritsarlik unvoni berilgan.',
                'image_url' => 'images/authors/artur-konan-doyl.webp',
            ],
            [
                'name' => 'Jek London',
                'birth_date' => '12.01.1876',
                'death_date' => '22.11.1916',
                'birth_place' => 'San-Frantsisko, Kaliforniya, AQSh',
                'nationality' => 'Amerikalik',
                'biography' => 'Jek London — amerikalik yozuvchi, jurnalist va ijtimoiy faol. Uning asarlari sarguzasht, tabiat va inson irodasini madh etadi.',
                'legacy' => '"Martin Iden", "Oq Qush", "Yovvoyi tabiat chaqirig\'i" jahon adabiyotining mashhur asarlari. AQShning birinchi millioner yozuvchisi sanaladi.',
                'image_url' => 'images/authors/jek-london.jpg',
            ],
            [
                'name' => 'Abdulla Qahhor',
                'birth_date' => '17.09.1907',
                'death_date' => '25.05.1968',
                'birth_place' => 'Qo\'qon, Farg\'ona viloyati',
                'nationality' => 'O\'zbek',
                'biography' => 'Abdulla Qahhor — o\'zbek yozuvchisi, dramaturg va tarjimon. U o\'zbek hikoyachiligining yetuk ustasi sifatida tanilgan.',
                'legacy' => '"Sarob", "Qo\'shchinor chiroqlari" romanlari, "Dahshat", "O\'g\'ri" hikoyalari adabiyotning oltin xazinasiga kirgan. O\'zbekiston Xalq yozuvchisi.',
                'image_url' => 'images/authors/abdulla-qahhor.jpg',
            ],
        ];

        $authorMap = [];
        foreach ($authors as $authorData) {
            $author = Author::create($authorData);
            $authorMap[$author->name] = $author->id;
        }

        $books = [
            [
                'title' => 'O\'tkan kunlar',
                'author' => 'Abdulla Qodiriy',
                'price' => 45000,
                'stock' => 10,
                'genre' => 'Roman',
                'year' => 1922,
                'description' => 'Otabek va Kumushning fojiaviy muhabbati haqida hikoya qiluvchi ilk o\'zbek romani.',
                'image_url' => 'images/books/otkan-kunlar.webp',
            ],
            [
                'title' => 'Sariq devni minib',
                'author' => 'Xudoyberdi To\'xtaboyev',
                'price' => 38000,
                'stock' => 25,
                'genre' => 'Sarguzasht',
                'year' => 1968,
                'description' => 'Hoshimjonning sehrli qalpoqcha yordamida qilgan qiziqarli sarguzashtlari.',
                'image_url' => 'images/books/sariq-devni-minib.webp',
            ],
            [
                'title' => 'Yulduzli tunlar',
                'author' => 'Pirimqul Qodirov',
                'price' => 52000,
                'stock' => 15,
                'genre' => 'Roman',
                'year' => 1978,
                'description' => 'Zahiriddin Muhammad Bobur hayoti va faoliyati haqida yirik polotno.',
                'image_url' => 'images/books/yulduzli-tunlar.webp',
            ],
            [
                'title' => 'Al-kimyogar',
                'author' => 'Paulo Koelo',
                'price' => 30000,
                'stock' => 40,
                'genre' => 'Falsafa',
                'year' => 1988,
                'description' => 'O\'z orzulari ortidan dunyoni kezib chiqqan Santyago hikoyasi.',
                'image_url' => 'images/books/al-kimyogar.webp',
            ],
            [
                'title' => 'Ikki eshik orasi',
                'author' => 'O\'tkir Hoshimov',
                'price' => 42000,
                'stock' => 20,
                'genre' => 'Roman',
                'year' => 1986,
                'description' => 'Urush va undan keyingi davr insonlar taqdiri, sadoqat va xiyonat haqida.',
                'image_url' => 'images/books/ikki-eshik-orasi.webp',
            ],
            [
                'title' => 'Dunyoning ishlari',
                'author' => 'O\'tkir Hoshimov',
                'price' => 35000,
                'stock' => 30,
                'genre' => 'Qissa',
                'year' => 1982,
                'description' => 'Ona siymosi va uning cheksiz mehri tarannum etilgan qalb amri asari.',
                'image_url' => 'images/books/dunyoning-ishlari.webp',
            ],
            [
                'title' => 'Kecha va kunduz',
                'author' => 'Cho\'lpon',
                'price' => 40000,
                'stock' => 12,
                'genre' => 'Roman',
                'year' => 1936,
                'description' => 'Zebining fojiali taqdiri orqali davr muammolari yoritilgan asar.',
                'image_url' => 'images/books/kecha-va-kunduz.webp',
            ],
            [
                'title' => 'Shaytanat',
                'author' => 'Tohir Malik',
                'price' => 150000,
                'stock' => 8,
                'genre' => 'Detektiv',
                'year' => 1994,
                'description' => 'Jinoyat olami va insoniylik kurashi haqidagi mashhur asar.',
                'image_url' => 'images/books/shaytanat.webp',
            ],
            [
                'title' => 'Kichkina shahzoda',
                'author' => 'Antuan de Sent-Ekzyuperi',
                'price' => 25000,
                'stock' => 50,
                'genre' => 'Falsafa',
                'year' => 1943,
                'description' => 'Bolalik nigohi bilan hayot haqiqatlarini anglash haqida.',
                'image_url' => 'images/books/kichkina-shahzoda.webp',
            ],
            [
                'title' => 'Molxona',
                'author' => 'Jorj Oruell',
                'price' => 28000,
                'stock' => 35,
                'genre' => 'Antiutopiya',
                'year' => 1945,
                'description' => 'Jamiyat va hokimiyatning o\'zgarishi haqidagi ramziy asar.',
                'image_url' => 'images/books/molxona.webp',
            ],
            [
                'title' => '1984',
                'author' => 'Jorj Oruell',
                'price' => 32000,
                'stock' => 18,
                'genre' => 'Antiutopiya',
                'year' => 1949,
                'description' => 'Totalitar tuzum va shaxs erkinligi cheklanishi haqida ogohlantiruvchi asar.',
                'image_url' => 'images/books/1984.webp',
            ],
            [
                'title' => 'Graf Monte-Kristo',
                'author' => 'Aleksandr Dyuma',
                'price' => 120000,
                'stock' => 10,
                'genre' => 'Sarguzasht',
                'year' => 1844,
                'description' => 'Xiyonat, qamoq va adolatli qasos hikoyasi.',
                'image_url' => 'images/books/graf-monte-kristo.webp',
            ],
            [
                'title' => 'Jinoyat va jazo',
                'author' => 'Fyodor Dostoyevskiy',
                'price' => 55000,
                'stock' => 14,
                'genre' => 'Roman',
                'year' => 1866,
                'description' => 'Raskolnikovning vijdon azobi va gunohidan qutulish yo\'li.',
                'image_url' => 'images/books/jinoyat-va-jazo.webp',
            ],
            [
                'title' => 'Boy ota, kambag\'al ota',
                'author' => 'Robert Kiyosaki',
                'price' => 45000,
                'stock' => 60,
                'genre' => 'Shaxsiy rivojlanish',
                'year' => 1997,
                'description' => 'Moliyaviy erkinlik va investitsiya asoslari haqida qo\'llanma.',
                'image_url' => 'images/books/boy-ota-kambagal-ota.webp',
            ],
            [
                'title' => 'Stiv Jobs',
                'author' => 'Uolter Ayzekson',
                'price' => 85000,
                'stock' => 5,
                'genre' => 'Biografiya',
                'year' => 2011,
                'description' => 'Apple asoschisining hayoti va innovatsion g\'oyalari tarixi.',
                'image_url' => 'images/books/stiv-jobs.webp',
            ],
            [
                'title' => 'Sapiens: Insoniyatning qisqacha tarixi',
                'author' => 'Yuval Noy Xarari',
                'price' => 70000,
                'stock' => 22,
                'genre' => 'Ilm-fan',
                'year' => 2011,
                'description' => 'Insoniyatning paydo bo\'lishidan hozirgi kungacha bosib o\'tgan yo\'li.',
                'image_url' => 'images/books/sapiens.webp',
            ],
            [
                'title' => 'Muvaffaqiyatli insonlarning 7 ko\'nikmasi',
                'author' => 'Stiven Kovi',
                'price' => 50000,
                'stock' => 15,
                'genre' => 'Shaxsiy rivojlanish',
                'year' => 1989,
                'description' => 'Samaradorlikni oshirish va maqsadlarga erishish qoidalari.',
                'image_url' => 'images/books/muvaffaqiyatli-insonlarning-7-konikmasi.webp',
            ],
            [
                'title' => 'Sherlok Xolms sarguzashtlari',
                'author' => 'Artur Konan Doyl',
                'price' => 48000,
                'stock' => 25,
                'genre' => 'Detektiv',
                'year' => 1892,
                'description' => 'Dunyodagi eng mashhur detektivning mantiqiy sirlarni ochishi.',
                'image_url' => 'images/books/sherlok-xolmsning-sarguzashtlari.webp',
            ],
            [
                'title' => 'Martin Iden',
                'author' => 'Jek London',
                'price' => 38000,
                'stock' => 12,
                'genre' => 'Roman',
                'year' => 1909,
                'description' => 'Oddiy dengizchining yozuvchi bo\'lish yo\'lidagi mashaqqatlari va sevgisi.',
                'image_url' => 'images/books/martin-iden.webp',
            ],
            [
                'title' => 'Dahshat',
                'author' => 'Abdulla Qahhor',
                'price' => 22000,
                'stock' => 10,
                'genre' => 'Hikoya',
                'year' => 1933,
                'description' => 'Inson ruhiyatidagi qo\'rquv va ijtimoiy muhitning ta\'siri haqida.',
                'image_url' => 'images/books/daxshat.webp',
            ],
        ];

        foreach ($books as $bookData) {
            $authorName = $bookData['author'];
            unset($bookData['author']);
            $bookData['author_id'] = $authorMap[$authorName];
            Book::create($bookData);
        }
    }
}
